import {
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElTabs,
  ElTabPane,
  ElCollapse,
  ElCollapseItem,
  ElForm,
  ElFormItem,
  ElInput,
  ElInputNumber,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElButton,
  ElButtonGroup,
  ElTable,
  ElTableColumn,
  ElPopover,
  ElMessage,
  ElMessageBox,
} from 'element-plus' // elementPlus按需加载


export const elementPlusComponentList = [
  ElMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElTabs,
  ElTabPane,
  ElCollapse,
  ElCollapseItem,
  ElForm,
  ElFormItem,
  ElInput,
  ElInputNumber,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElButton,
  ElButtonGroup,
  ElTable,
  ElTableColumn,
  ElPopover,
  ElMessage,
  ElMessageBox,
]